import { deepFreeze } from './immutable.js';

export const DATASET_SPLIT_LEAKAGE_FINDING_TYPE = deepFreeze({
  SOURCE_DATASET_INTEGRITY_INVALID: 'SOURCE_DATASET_INTEGRITY_INVALID',
  SOURCE_DATASET_INTEGRITY_INCOMPLETE: 'SOURCE_DATASET_INTEGRITY_INCOMPLETE',
  SOURCE_DATASET_IDENTITY_MISMATCH: 'SOURCE_DATASET_IDENTITY_MISMATCH',
  SOURCE_DATASET_OPERATIONAL_DRIFT: 'SOURCE_DATASET_OPERATIONAL_DRIFT',
  INVALID_PARTITION: 'INVALID_PARTITION',
  INVALID_PERIOD: 'INVALID_PERIOD',
  PARTITION_PERIOD_OUT_OF_ORDER: 'PARTITION_PERIOD_OUT_OF_ORDER',
  PARTITION_PERIOD_OVERLAP: 'PARTITION_PERIOD_OVERLAP',
  PARTITION_SOURCE_IDENTITY_MISMATCH: 'PARTITION_SOURCE_IDENTITY_MISMATCH',
  DUPLICATE_PARTITION_TYPE: 'DUPLICATE_PARTITION_TYPE',
  DUPLICATE_PARTITION_OBSERVATION: 'DUPLICATE_PARTITION_OBSERVATION',
  DUPLICATE_PARTITION_SPIN: 'DUPLICATE_PARTITION_SPIN',
  MISSING_SOURCE_OBSERVATION: 'MISSING_SOURCE_OBSERVATION',
  MISSING_SOURCE_SPIN: 'MISSING_SOURCE_SPIN',
  UNEXPECTED_PARTITION_OBSERVATION: 'UNEXPECTED_PARTITION_OBSERVATION',
  UNEXPECTED_PARTITION_SPIN: 'UNEXPECTED_PARTITION_SPIN',
  OBSERVATION_OUTSIDE_PARTITION_PERIOD: 'OBSERVATION_OUTSIDE_PARTITION_PERIOD',
  SPIN_TIMESTAMP_CONFLICT: 'SPIN_TIMESTAMP_CONFLICT',
  COUNT_MISMATCH: 'COUNT_MISMATCH',
  SOURCE_OBSERVATION_INVALID: 'SOURCE_OBSERVATION_INVALID',
});

export function isDatasetSplitLeakageFindingType(value) {
  return Object.values(DATASET_SPLIT_LEAKAGE_FINDING_TYPE).includes(value);
}
